export const profanityList = [
  'fuck', 'fuk', 'fck', 'fuc', 'fuq',
  'shit', 'sht', 'shyt',
  'ass', 'azz',
  'bitch', 'btch', 'b1tch',
  'damn', 'dmn',
  'cunt', 'cnt',
  'dick', 'd1ck', 'dik',
  'cock', 'cok', 'c0ck',
  'pussy', 'puss', 'psy',
  'fag', 'faggot', 'f4g', 'gay', 'g4y', 'gey',
  'nigger', 'nigga', 'n1gger', 'n1gga', 'niga', 'nigg',
  'retard', 'retrd',
  'slut', 'sl0t',
  'whore', 'wh0re', 'h0e', 'hoe',
  'bastard', 'bstrd',
  'piss', 'pss',
  'crap',
  'twat',
  'wanker', 'wnkr',
  'douche',
  'jackass',
  'motherfucker', 'mf', 'mofo',
  'stfu', 'gtfo',
  'kys',
  'porn', 'prn',
  'nude', 'nudes',
  'sex', 'sexx',
  'penis', 'pnis',
  'vagina', 'vag',
  'boob', 'tit', 'titty',
  'cum', 'jizz',
  'anal', 'anus',
  'rape', 'rapist',
  'molest',
  'pedo', 'pedophile',
];

export const religiousTermsList = [
  'god', 'g0d',
  'jesus', 'jsus',
  'christ', 'chrst',
  'allah',
  'muhammad', 'mohammed', 'mohamed',
  'buddha',
  'satan', 'lucifer',
  'devil', 'dvil',
  'hell', 'h3ll',
  'heaven', 'hven',
  'bible', 'bibl',
  'quran', 'koran',
  'torah',
  'church',
  'mosque',
  'temple',
  'holy',
  'angel',
  'demon',
  'prayer', 'pray',
  'gospel',
  'prophet',
  'messiah',
  'psalm',
  'apostle',
  'jihad',
  'christian', 'muslim', 'jewish', 'hindu', 'buddhist',
  'atheist',
  'agnostic',
  'cult',
  'sect',
  'heretic',
  'blasphemy',
  'sinner', 'sin',
];
